// Mock tmux state — 6 sessions, ~22 windows, mix of agents + shells
// Inspired by the periscope concept but with original data and naming.

const NOW = Date.now();
const m = (mins) => NOW - mins * 60 * 1000;
const s = (secs) => NOW - secs * 1000;

const SESSIONS = [
  {
    id: "main",
    name: "main",
    attached: true,
    created: m(60 * 8),
    clients: [{ tty: "/dev/ttys012", term: "iTerm2", since: m(60 * 7) }],
  },
  {
    id: "agents",
    name: "agents",
    attached: false,
    created: m(60 * 4),
    clients: [],
  },
  {
    id: "review",
    name: "review",
    attached: false,
    created: m(60 * 2),
    clients: [],
  },
  {
    id: "ops",
    name: "ops",
    attached: false,
    created: m(60 * 26),
    clients: [],
  },
  {
    id: "scratch",
    name: "scratch",
    attached: false,
    created: m(60 * 50),
    clients: [],
  },
];

// status: idle | running | waiting | done | error
// kind: shell | editor | server | agent | logs
const WINDOWS = [
  // ── main ──────────────────────────────────────────────────────────────
  {
    id: "main:0",
    session: "main",
    index: 0,
    name: "nvim",
    kind: "editor",
    status: "idle",
    lastActivity: s(14),
    cpu: 2.1,
    mem: 318,
    cmd: "nvim src/dashboard.tsx",
    cwd: "~/work/switchboard",
    preview: [
      "  42 │   const [filter, setFilter] = useState('all');",
      "  43 │   const visible = windows.filter(w => filter === 'all'",
      "  44 │     || w.status === filter);",
      "  45 │ ",
      "  46 │   return (",
      "  47 │     <Kanban sessions={sessions}>",
      "  48 │       {visible.map(w => <WindowCard key={w.id} w={w} />)}",
      "  49 │     </Kanban>",
      "  50 │   );",
    ],
  },
  {
    id: "main:1",
    session: "main",
    index: 1,
    name: "dev",
    kind: "server",
    status: "running",
    lastActivity: s(2),
    cpu: 38.4,
    mem: 1240,
    cmd: "pnpm dev",
    cwd: "~/work/switchboard",
    preview: [
      "  VITE v5.4.10  ready in 312 ms",
      "  ➜  Local:   http://localhost:5173/",
      "  ➜  Network: use --host to expose",
      "",
      "  10:42:18  HMR update /src/dashboard.tsx",
      "  10:42:31  HMR update /src/cards.tsx",
      "  10:42:47  HMR update /src/dashboard.tsx",
    ],
  },
  {
    id: "main:2",
    session: "main",
    index: 2,
    name: "claude/dashboard-kanban",
    kind: "agent",
    status: "waiting",
    pendingInput: true,
    lastActivity: s(38),
    cpu: 4.3,
    mem: 412,
    cmd: "claude --resume",
    cwd: "~/work/switchboard",
    agent: {
      branch: "feat/kanban-cols",
      pr: 184,
      ci: "passing",
      spinner: null,
      recap: "Refactored card density modes; awaiting confirmation to drop the legacy grid layout.",
      action: "Approve drop of legacy GridView?  (y/n)",
    },
    preview: [
      "  ● Refactored card density modes into a single variant prop.",
      "  ● Updated tweaks panel to read density from useTweaks().",
      "",
      "  ✻ I can drop the old GridView component entirely — it's no longer",
      "    referenced. Want me to delete src/grid-view.tsx?",
      "",
      "  > _",
    ],
  },
  {
    id: "main:3",
    session: "main",
    index: 3,
    name: "shell",
    kind: "shell",
    status: "idle",
    lastActivity: m(12),
    cpu: 0.0,
    mem: 18,
    cmd: "zsh",
    cwd: "~/work/switchboard",
    preview: [
      "$ git status",
      "On branch feat/kanban-cols",
      "Your branch is ahead of 'origin/feat/kanban-cols' by 2 commits.",
      "",
      "nothing to commit, working tree clean",
      "$ _",
    ],
  },

  // ── agents ────────────────────────────────────────────────────────────
  {
    id: "agents:0",
    session: "agents",
    index: 0,
    name: "claude/migrate-orm",
    kind: "agent",
    status: "running",
    lastActivity: s(1),
    cpu: 12.7,
    mem: 624,
    cmd: "claude --dangerously-skip-permissions",
    cwd: "~/work/api-core",
    agent: {
      branch: "chore/prisma-to-drizzle",
      pr: 412,
      ci: "running",
      spinner: "writing accounts migration",
      duration: "42s",
      recap: "Migrating ORM from Prisma to Drizzle across 47 models.",
    },
    preview: [
      "  ✻ Generating drizzle schema for table 'accounts'…",
      "  ✓ wrote db/schema/accounts.ts",
      "  ✻ Generating drizzle schema for table 'sessions'…",
      "  ⠹ thinking",
    ],
  },
  {
    id: "agents:1",
    session: "agents",
    index: 1,
    name: "claude/flaky-tests",
    kind: "agent",
    status: "waiting",
    pendingInput: true,
    lastActivity: s(94),
    cpu: 0.4,
    mem: 388,
    cmd: "claude",
    cwd: "~/work/api-core",
    agent: {
      branch: "fix/flaky-billing-tests",
      pr: null,
      ci: "failing",
      spinner: null,
      recap: "Found 3 candidate flake sources. Needs decision on retry policy.",
      action: "Adopt 3× retry on network-bound tests?  [y/N/details]",
    },
    preview: [
      "  ● tests/billing/invoice.spec.ts:42  intermittent timeout",
      "  ● tests/billing/refund.spec.ts:88   race on webhook receipt",
      "  ● tests/billing/proration.spec.ts   nondeterministic clock",
      "",
      "  ✻ Want me to apply 3× retry on network-bound tests, or",
      "    fix each at the source?",
      "  > _",
    ],
  },
  {
    id: "agents:2",
    session: "agents",
    index: 2,
    name: "claude/landing-copy",
    kind: "agent",
    status: "done",
    lastActivity: m(4),
    cpu: 0.1,
    mem: 244,
    cmd: "claude",
    cwd: "~/work/marketing",
    agent: {
      branch: "copy/landing-v3",
      pr: 27,
      ci: "passing",
      spinner: null,
      recap: "Rewrote hero + 3 feature blocks; PR opened, CI green.",
    },
    preview: [
      "  ✓ Wrote hero.md",
      "  ✓ Wrote features.md",
      "  ✓ Opened PR #27 → main",
      "",
      "  Done. CI is green; ready for review.",
      "  > _",
    ],
  },
  {
    id: "agents:3",
    session: "agents",
    index: 3,
    name: "claude/perf-investigation",
    kind: "agent",
    status: "running",
    lastActivity: s(6),
    cpu: 87.4,
    mem: 1880,
    cmd: "claude",
    cwd: "~/work/api-core",
    agent: {
      branch: "perf/timeline-render",
      pr: null,
      ci: null,
      spinner: "profiling render hotpath",
      duration: "4m 12s",
      recap: "Investigating 800ms timeline render regression after v2.1.",
    },
    preview: [
      "  ✻ Running flamegraph on TimelineView render…",
      "  ⠼ collecting samples (12s elapsed)",
    ],
  },
  {
    id: "agents:4",
    session: "agents",
    index: 4,
    name: "claude/docs-cleanup",
    kind: "agent",
    status: "error",
    lastActivity: m(2),
    cpu: 0.0,
    mem: 198,
    cmd: "claude",
    cwd: "~/work/docs",
    agent: {
      branch: "docs/sweep",
      pr: null,
      ci: null,
      spinner: null,
      recap: "Stopped: rate limit hit on the Anthropic API.",
    },
    preview: [
      "  ✓ Rewrote getting-started.md",
      "  ✓ Rewrote concepts/sessions.md",
      "  ✗ Error: rate_limit_exceeded (retry after 47s)",
      "  > _",
    ],
  },

  // ── review ────────────────────────────────────────────────────────────
  {
    id: "review:0",
    session: "review",
    index: 0,
    name: "PR #184",
    kind: "editor",
    status: "idle",
    lastActivity: m(8),
    cpu: 0.2,
    mem: 88,
    cmd: "gh pr diff 184 | delta",
    cwd: "~/work/switchboard",
    preview: [
      "  diff --git a/src/dashboard.tsx b/src/dashboard.tsx",
      "  @@ -42,7 +42,9 @@ export function Dashboard() {",
      "  -  return <Grid>{cards}</Grid>;",
      "  +  return layout === 'kanban'",
      "  +    ? <Kanban sessions={sessions}>{cards}</Kanban>",
      "  +    : <Grid>{cards}</Grid>;",
    ],
  },
  {
    id: "review:1",
    session: "review",
    index: 1,
    name: "PR #412",
    kind: "editor",
    status: "idle",
    lastActivity: m(14),
    cpu: 0.1,
    mem: 74,
    cmd: "gh pr diff 412 | delta",
    cwd: "~/work/api-core",
    preview: [
      "  diff --git a/db/schema/accounts.ts b/db/schema/accounts.ts",
      "  +export const accounts = pgTable('accounts', {",
      "  +  id: uuid('id').primaryKey().defaultRandom(),",
      "  +  email: text('email').notNull().unique(),",
      "  +  createdAt: timestamp('created_at').defaultNow().notNull(),",
      "  +});",
    ],
  },
  {
    id: "review:2",
    session: "review",
    index: 2,
    name: "notes",
    kind: "editor",
    status: "idle",
    lastActivity: m(22),
    cpu: 0.0,
    mem: 32,
    cmd: "nvim review-notes.md",
    cwd: "~/work/switchboard",
    preview: [
      "  # Review notes — 2026-05-13",
      "",
      "  ## #184 (dashboard kanban)",
      "  - ask about density default",
      "  - confirm grid view drop is safe",
    ],
  },

  // ── ops ───────────────────────────────────────────────────────────────
  {
    id: "ops:0",
    session: "ops",
    index: 0,
    name: "deploy",
    kind: "logs",
    status: "running",
    lastActivity: s(4),
    cpu: 64.2,
    mem: 2240,
    cmd: "fly logs -a api-prod",
    cwd: "~/work/api-core",
    preview: [
      "  2026-05-13T17:42:18Z  http GET /v1/accounts/me 200 in 42ms",
      "  2026-05-13T17:42:19Z  http POST /v1/invoices 201 in 118ms",
      "  2026-05-13T17:42:20Z  http GET /v1/billing/usage 200 in 31ms",
      "  2026-05-13T17:42:21Z  http GET /v1/accounts/me 200 in 28ms",
    ],
  },
  {
    id: "ops:1",
    session: "ops",
    index: 1,
    name: "k9s",
    kind: "logs",
    status: "running",
    lastActivity: s(1),
    cpu: 3.4,
    mem: 244,
    cmd: "k9s --context prod",
    cwd: "~",
    preview: [
      "  NAMESPACE  NAME              READY  STATUS    RESTARTS  AGE",
      "  api        api-7f8c-9zhpw    1/1    Running   0         3h14m",
      "  api        api-7f8c-jjk2x    1/1    Running   0         3h14m",
      "  worker     worker-4d-rmm22   1/1    Running   1         3h14m",
    ],
  },
  {
    id: "ops:2",
    session: "ops",
    index: 2,
    name: "alerts",
    kind: "shell",
    status: "idle",
    lastActivity: m(34),
    cpu: 0.0,
    mem: 12,
    cmd: "zsh",
    cwd: "~",
    preview: [
      "$ # nothing firing — last alert 6h ago",
      "$ _",
    ],
  },

  // ── scratch ───────────────────────────────────────────────────────────
  {
    id: "scratch:0",
    session: "scratch",
    index: 0,
    name: "shell",
    kind: "shell",
    status: "idle",
    lastActivity: m(48),
    cpu: 0.0,
    mem: 14,
    cmd: "zsh",
    cwd: "~",
    preview: ["$ _"],
  },
  {
    id: "scratch:1",
    session: "scratch",
    index: 1,
    name: "psql",
    kind: "shell",
    status: "idle",
    lastActivity: m(120),
    cpu: 0.0,
    mem: 42,
    cmd: "psql -d switchboard_dev",
    cwd: "~",
    preview: [
      "  switchboard_dev=# select count(*) from sessions;",
      "   count ",
      "  -------",
      "       6",
      "  (1 row)",
      "  switchboard_dev=# _",
    ],
  },
  {
    id: "scratch:2",
    session: "scratch",
    index: 2,
    name: "htop",
    kind: "logs",
    status: "running",
    lastActivity: s(2),
    cpu: 0.6,
    mem: 28,
    cmd: "htop",
    cwd: "~",
    preview: [
      "    1  CPU[||||         12.4%]   Tasks: 412, 2 thr; 3 running",
      "    2  CPU[|||||||      24.1%]   Load: 1.42 1.18 0.98",
      "    Mem[||||||||||||||  18.2G/64G]",
    ],
  },
  {
    id: "scratch:3",
    session: "scratch",
    index: 3,
    name: "claude/scratch",
    kind: "agent",
    status: "idle",
    lastActivity: m(96),
    cpu: 0.0,
    mem: 188,
    cmd: "claude",
    cwd: "~/scratch",
    agent: {
      branch: null,
      pr: null,
      ci: null,
      spinner: null,
      recap: "Quick experiments; idle since this morning.",
    },
    preview: [
      "  ✻ ready",
      "  > _",
    ],
  },
];

const STATUS_META = {
  running:  { label: "running",  tone: "cyan"   },
  waiting:  { label: "waiting",  tone: "amber"  },
  idle:     { label: "idle",     tone: "gray"   },
  done:     { label: "done",     tone: "green"  },
  error:    { label: "error",    tone: "red"    },
};

function formatAgo(ts) {
  const diff = Math.max(0, Date.now() - ts);
  const s = Math.floor(diff / 1000);
  if (s < 60)   return `${s}s`;
  const mn = Math.floor(s / 60);
  if (mn < 60)  return `${mn}m`;
  const h = Math.floor(mn / 60);
  if (h < 24)   return `${h}h`;
  const d = Math.floor(h / 24);
  return `${d}d`;
}

function formatMem(mb) {
  if (mb < 1024) return `${mb} MB`;
  return `${(mb / 1024).toFixed(1)} GB`;
}

Object.assign(window, {
  SESSIONS,
  WINDOWS,
  STATUS_META,
  formatAgo,
  formatMem,
});
